//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 10:41:04 AM BRT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "https://www.camara.gov.br/SitCamaraWS/Deputados", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.github.luiguip.chamber_of_deputies_service.infrastructure.deputados.model.wsdl;
