//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.07 at 10:41:04 AM BRT 
//


package com.github.luiguip.chamber_of_deputies_service.infrastructure.deputies.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.github.luiguip.chamber_of_deputies_service.infrastructure.deputies.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.github.luiguip.chamber_of_deputies_service.infrastructure.deputies.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ObterPartidosCDResponse }
     * 
     */
    public ObterPartidosCDResponse createObterPartidosCDResponse() {
        return new ObterPartidosCDResponse();
    }

    /**
     * Create an instance of {@link ObterPartidosBlocoCDResponse }
     * 
     */
    public ObterPartidosBlocoCDResponse createObterPartidosBlocoCDResponse() {
        return new ObterPartidosBlocoCDResponse();
    }

    /**
     * Create an instance of {@link ObterLideresBancadasResponse }
     * 
     */
    public ObterLideresBancadasResponse createObterLideresBancadasResponse() {
        return new ObterLideresBancadasResponse();
    }

    /**
     * Create an instance of {@link ObterIdCadastroOrcamentoResponse }
     * 
     */
    public ObterIdCadastroOrcamentoResponse createObterIdCadastroOrcamentoResponse() {
        return new ObterIdCadastroOrcamentoResponse();
    }

    /**
     * Create an instance of {@link ObterDetalhesDeputadoResponse }
     * 
     */
    public ObterDetalhesDeputadoResponse createObterDetalhesDeputadoResponse() {
        return new ObterDetalhesDeputadoResponse();
    }

    /**
     * Create an instance of {@link ObterDeputadosResponse }
     * 
     */
    public ObterDeputadosResponse createObterDeputadosResponse() {
        return new ObterDeputadosResponse();
    }

    /**
     * Create an instance of {@link ObterPartidosCD }
     * 
     */
    public ObterPartidosCD createObterPartidosCD() {
        return new ObterPartidosCD();
    }

    /**
     * Create an instance of {@link ObterPartidosCDResponse.ObterPartidosCDResult }
     * 
     */
    public ObterPartidosCDResponse.ObterPartidosCDResult createObterPartidosCDResponseObterPartidosCDResult() {
        return new ObterPartidosCDResponse.ObterPartidosCDResult();
    }

    /**
     * Create an instance of {@link ObterPartidosBlocoCD }
     * 
     */
    public ObterPartidosBlocoCD createObterPartidosBlocoCD() {
        return new ObterPartidosBlocoCD();
    }

    /**
     * Create an instance of {@link ObterPartidosBlocoCDResponse.ObterPartidosBlocoCDResult }
     * 
     */
    public ObterPartidosBlocoCDResponse.ObterPartidosBlocoCDResult createObterPartidosBlocoCDResponseObterPartidosBlocoCDResult() {
        return new ObterPartidosBlocoCDResponse.ObterPartidosBlocoCDResult();
    }

    /**
     * Create an instance of {@link ObterLideresBancadas }
     * 
     */
    public ObterLideresBancadas createObterLideresBancadas() {
        return new ObterLideresBancadas();
    }

    /**
     * Create an instance of {@link ObterLideresBancadasResponse.ObterLideresBancadasResult }
     * 
     */
    public ObterLideresBancadasResponse.ObterLideresBancadasResult createObterLideresBancadasResponseObterLideresBancadasResult() {
        return new ObterLideresBancadasResponse.ObterLideresBancadasResult();
    }

    /**
     * Create an instance of {@link ObterIdCadastroOrcamento }
     * 
     */
    public ObterIdCadastroOrcamento createObterIdCadastroOrcamento() {
        return new ObterIdCadastroOrcamento();
    }

    /**
     * Create an instance of {@link ObterIdCadastroOrcamentoResponse.ObterIdCadastroOrcamentoResult }
     * 
     */
    public ObterIdCadastroOrcamentoResponse.ObterIdCadastroOrcamentoResult createObterIdCadastroOrcamentoResponseObterIdCadastroOrcamentoResult() {
        return new ObterIdCadastroOrcamentoResponse.ObterIdCadastroOrcamentoResult();
    }

    /**
     * Create an instance of {@link ObterDetalhesDeputado }
     * 
     */
    public ObterDetalhesDeputado createObterDetalhesDeputado() {
        return new ObterDetalhesDeputado();
    }

    /**
     * Create an instance of {@link ObterDetalhesDeputadoResponse.ObterDetalhesDeputadoResult }
     * 
     */
    public ObterDetalhesDeputadoResponse.ObterDetalhesDeputadoResult createObterDetalhesDeputadoResponseObterDetalhesDeputadoResult() {
        return new ObterDetalhesDeputadoResponse.ObterDetalhesDeputadoResult();
    }

    /**
     * Create an instance of {@link ObterDeputados }
     * 
     */
    public ObterDeputados createObterDeputados() {
        return new ObterDeputados();
    }

    /**
     * Create an instance of {@link ObterDeputadosResponse.ObterDeputadosResult }
     * 
     */
    public ObterDeputadosResponse.ObterDeputadosResult createObterDeputadosResponseObterDeputadosResult() {
        return new ObterDeputadosResponse.ObterDeputadosResult();
    }

}
